name: Deploy Laravel Project

on:
  push:
    branches: [ main ] # Executa ao dar push na branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # 1. Instalar dependências e Compilar (PHP e JS)
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, gd, zip

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader --no-scripts

    - name: Install NPM Dependencies & Build
      run: |
        npm install
        npm run build

    - name: Generate Deploy Timestamp
      run: echo $(TZ='America/Sao_Paulo' date +'%d/%m/%Y %H:%M:%S') > storage/app/deploy_time.txt

    - name: Create Clean Deployment Zip
      run: |
        zip -r deploy.zip . \
        -x ".git/*" \
        -x ".idea/*" \
        -x ".env" \
        -x "public/hot/*" \
        -x "node_modules/*" \
        -x "storage/framework/*" \
        -x "storage/logs/*" \
        -x "tests/*" \
        -x ".editorconfig" \
        -x ".gitignore" \
        -x ".env.example" \
        -x "phpunit.xml" \
        -x "postcss.config.js" \
        -x "README.md" \
        -x "package.json" \
        -x "package-lock.json" \
        -x "vite.config.js" \
        -x "tailwind.config.js" \
        -x "build.bat" \
        -x "public/hot"

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Envia o conteúdo da pasta atual
        server-dir: /apps/ # Ou o caminho da sua pasta no servido
        exclude: |
          **
          !deploy.zip

    # 4. Acessar URL para descompactar
    - name: Trigger Unzip via URL
      run: curl -s https://apps.spigo.net/unzip-script.php?token=${{ secrets.DEPLOY_TOKEN }}